name: Build Simple Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x android-simple/gradlew
    
    - name: Build with Gradle
      run: |
        cd android-simple
        ./gradlew assembleDebug --stacktrace
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: rbc-wealthpath-simple.apk
        path: android-simple/app/build/outputs/apk/debug/app-debug.apk